<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-A92F397" failures="0" tests="1" name="restAssureTest.CAServer_PUT" time="0.594" errors="1" timestamp="05 Feb 2018 12:58:53 GMT" skipped="0">
  <testcase classname="restAssureTest.CAServer_PUT" name="testPUT" time="0.594">
    <error message="javax.xml.bind.JAXBException
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: javax.xml.bind.JAXBException - with linked exception:[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]at io.restassured.mapper.factory.DefaultJAXBObjectMapperFactory.create(DefaultJAXBObjectMapperFactory.java:30)at io.restassured.mapper.factory.DefaultJAXBObjectMapperFactory.create(DefaultJAXBObjectMapperFactory.java:25)at io.restassured.mapper.factory.ObjectMapperFactory$create.call(Unknown Source)at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)at io.restassured.internal.mapping.JaxbMapper.serialize(JaxbMapper.groovy:46)at io.restassured.mapper.ObjectMapper$serialize.call(Unknown Source)at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)at io.restassured.internal.mapping.ObjectMapping.serializeWithJaxb(ObjectMapping.groovy:186)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base/java.lang.reflect.Method.invoke(Unknown Source)at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)at io.restassured.internal.mapping.ObjectMapping.serialize(ObjectMapping.groovy:123)at io.restassured.internal.mapping.ObjectMapping$serialize.call(Unknown Source)at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)at io.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:831)at restAssureTest.CAServer_PUT.testPUT(CAServer_PUT.java:77)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base/java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: javax.xml.bind.JAXBException - with linked exception:[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:241)at javax.xml.bind.ContextFinder.find(ContextFinder.java:477)at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:656)at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)at io.restassured.mapper.factory.DefaultJAXBObjectMapperFactory.create(DefaultJAXBObjectMapperFactory.java:28)... 52 moreCaused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactoryat java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)at java.base/java.lang.ClassLoader.loadClass(Unknown Source)at javax.xml.bind.ContextFinder.safeLoadClass(ContextFinder.java:594)at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:239)... 56 more]]>
    </error>
  </testcase> <!-- testPUT -->
</testsuite> <!-- restAssureTest.CAServer_PUT -->
